package com.github.mjaulin.springbootkotlin

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable

@DynamoDBTable(tableName = "Task")
class Task {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey
    var id: String? = null

    @DynamoDBAttribute
    var label: String? = null

    @DynamoDBAttribute
    var completed: Boolean = false
}